cuba , senegal , angola , EI salvador, cameroon, italy, ireland,leben…
Daniel-Ioannou/flutter_currency_picker pull request #96
Opened 2024-01-21 15:53 UTC by maheshwaran-p

## Summary

This pull request adds support for the following new currencies: Cuba, Senegal, Angola, El Salvador, Cameroon, Italy, Ireland, Lebanon, Mali, Malta, Madagascar, Togo, and Tonga.

### Changes Made

- Added new currencies to the currency list.
- Updated the country flags associated with the new currencies.

2024-01-30 10:36 UTC, MLZ91 commented
Why do you want to add Italy and Ireland for example? It is a currency list not a country list.

2024-01-31 19:16 UTC, Daniel-Ioannou requested changes
Of the currencies you added, only the Tongan paʻanga, Malagasy ariary, Angolan kwanza, and Lebanese pound are missing from the list. Please remove the rest. This is a currency picker, not a country picker. The Euro is used by 26 countries, so we cannot add the euro 26 times."

2024-01-31 19:16 UTC, Daniel-Ioannou commented on lib/src/currencies.dart
> +    "code": "XOF",
West African CFA Franc(XOF) it is already in the currency list

2024-01-31 19:16 UTC, Daniel-Ioannou commented on lib/src/currencies.dart
> +    "code": "USD",
United States Dollar (USD) it is already in the currency list

2024-01-31 19:16 UTC, Daniel-Ioannou commented on lib/src/currencies.dart
> +    "code": "XAF",
Central African CFA franc(XAF) it is already in the currency list

2024-02-29 17:49 UTC, closed without merging